[package]
name = "recholera"
version = "0.1.0"
authors = ["Christian Dürr <contact@christianduerr.com>"]

[dev-dependencies]
tempdir = "0.3.5"

[dependencies]
error-chain = "0.10.0"
walkdir = "1.0.7"
regex = "0.2.2"
clap = "2.24.2"
